### ISSUE TITLE
Android build issue 4.14.9 due to allowBackup setting

### ISSUE THREAD

**Issue by arendjantetteroo** [Cap-go/capacitor-updater#139]
I get this in version 4.14.9

```
/appbuild/android/app/src/debug/AndroidManifest.xml:15:9-35 Error:
	Attribute application@allowBackup value=(true) from AndroidManifest.xml:15:9-35
	is also present at [:capgo-capacitor-updater] AndroidManifest.xml:10:9-36 value=(false).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:21:5-54:19 to override.
See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
```
``
Caused by this commit: 
https://github.com/Cap-go/capacitor-updater/commit/2fe3f8ba529d636d102935b720b0c6d1a8dc676d

Can you enlighten me on the reason for adding this? Apparently this setting is true for my app, any reason to set it to false?

**Comment by riderx** [comment]
it was sonarcloud security recommendation. I can't find it back in they interface, but they point was, by default backup is allowed where it shouldn't unleast you are sure it make sense.
otherwise for exemple your users could use adb to extract backup file from your app.

i will check if i can herit from parent

**Comment by riderx** [comment]
So i removed it until i find a better solution
