### ISSUE TITLE
feat: Allow send changelog info with update

### ISSUE THREAD

**Issue by riderx** [Cap-go/capacitor-updater#189]
### Description
The goal is this is to allow display what did changed after the update.

So i require a chagelog field in DB and getChangelog method in IOS and Android

### Platform(s)
Both IOS and Android

**Comment by simonflk** [comment]
This would be great.

A few extra thoughts:

* Ability to set the changelog at the point of upload, or via an API call so that we can set it from a github action
* View/Set changelog via webapp
* If user updates from 1.2.0 to 1.2.8, then `getChangelog()` should be able to fetch all the changes since 1.2.0 not just for the latest version

**Comment by riderx** [comment]
This is outside Capgo field and will let you create that at the bundle level
