### ISSUE TITLE
feat: set channel in capacitor config

### ISSUE THREAD

**Issue by riderx** [Cap-go/capacitor-updater#304]
### Description
Currently some users set channel for every users at JS boot.
The issue is, set channel is done after the first contact to Capgo backend so the users could receive an not wanted update.

### Platform(s)
iOS and android

### Preferred Solution
The channel is set in the capacitor config, and send in every request for updates.

This require to change Capgo backend to accept the channel in the update payload.

setChannel should allow still to override it, if allowed in the config with something like « overrideConfigChannel: boolean 

if no channel in the config, then this boolean is ignored and setChannel always work.

**Comment by seveves** [comment]
Normally "production" stage is our default channel and there is no need to call setChannel on app startup. But it is possible to switch our app to run against another stage like test or dev and then we need to call setChannel. At the moment we have one init logic and this one is called as soon as the user switches to another stage and therefore we implemented the setChannel inside this logic and that's why we call this on every app startup. Definetely something that we can change in our code but maybe it would be nice to pass the environment/channel in the notifyAppReady call because this one we need to call on every app startup, right?

**Comment by riderx** [comment]
Thanks @seveves for the comment, notifyAppReady should always be called, but right now this is still called after the native code do the first call to Capgo backend, and this is a limit of Capacitor, i could change the whole logic and wait a signal from the JS to start the Update like manual mode, but i believe allow channel in the config is a better option for automatic mode, what do you think ?

**Comment by ap1969** [comment]
Hi Martin,
I like this idea. If it's in config, it's easy to work within the build process to change it to a channel appropriate to the dev/prod/whatever app/environment.
Andy

**Comment by riderx** [comment]
This has been released in https://www.npmjs.com/package/@capgo/capacitor-updater/v/5.5.0
And it's taken to account in Capgo backend here:
https://github.com/Cap-go/capgo/tree/10.454.0
I let you test it, default channel will override any other settings in channel, channel override or device override.
