### ISSUE TITLE
feat: ability to update your app on first start

### ISSUE THREAD

**Issue by FernetB** [Cap-go/capacitor-updater#319]
### Description

Hi, first of all, awesome plugin, and thanks for everything!

My feature/question is:

It is possible to, on your first start, download the live update and do the changes while in foreground?

Because we need that the live update that we do impacts instantly and not when the user sends the app to background.

I don't know if currently we can do that, we are using the auto update flag with our own hosting

Cheers!

**Comment by FernetB** [comment]
Hi! I saw recently that there is a config 
`
"CapacitorUpdater": {
      "directUpdate": true,
    }
`
that does that. 
My question is, can i put something like o loading screen with text for that, and where i can find the progress % to do that?

**Comment by riderx** [comment]
You have the event listener with the download % for that.
I developed this for a big client bug we stopped using it, that makes terrible experience for users, they download the app then open it and wait again for more download, this is also against app store rules outside video games.

**Comment by FernetB** [comment]
Sorry, but could you specify what is exactly against the rules?

Additionally, how do you manage to ensure that all users immediately receive the latest updates, especially in scenarios requiring urgent bug fixes that cannot wait for users to switch their apps from background to foreground to initiate the update?

**Comment by riderx** [comment]
Yes, 
Display to the user when it opens the app a screen saying "download update" is against the rules.

You need to find alternative things saying "tayloring your experience" or something like that, but at any moment, Google and specially Apple can block you to do app store update.

If you use direct update, the check will be done next time they open the app, and block them to using the app until the update is done.

There is no process to "immediately receive the latest updates" at any given time.

I did some R&D on this but that not an easy task, the best way would be to implement background notification.
But that means The server has to be connected to your Apple Account for the notification system, and you cannot use Firebase, it has to be implemented from the ground.

So because of that right now, we have only this system who is equivalent to all others providers and making the update porcess already way better than. waiting days with Apple and Google way.

**Comment by FernetB** [comment]
Hey, i dont understand the part of 
> and block them to using the app until the update is done.

I tried the direct update and does not block the user, it does all from behind until the new app is reloaded. What is the problem to not block the user on that? it takes just a few seconds to do the update, I guess the problem is if the app is too heavy and u let the user use it and then sundenly is restarted i'm right?

**Comment by riderx** [comment]
@FernetB correct it doesn't block the user, you have to do it.
I wanted to create this solution, but I cannot do it with Capacitor, or I cannot understand how.

The update takes a few seconds at home on your Wi-Fi, on the go it's another story.
Depending on your users and their device, it can be long.

So the user will start using it and then got the restart, you are correct.

With direct update, as same without, the check is done at first start and every foregrounding of the app.
The only difference is in direct mode the update is applied directly, instead of waiting for the next background.

**Comment by FernetB** [comment]
Ahh nice, thanks for clarify!
