### ISSUE TITLE
feat: Allow changing request method for updateUrl

### ISSUE THREAD

**Issue by berkcambaz** [Cap-go/capacitor-updater#401]
### Description
Currently, requests made to the `updateUrl` use the POST method, and it can't be changed. This makes implementing the `Over-the-Air` feature harder for offline apps that don't have a backend. Using GitHub Pages or Cloudflare Pages, it's possible to serve the update bundle, but it's not possible to serve the `updates.json` as it's only accessible via a POST request.

### Platform(s)
Android & iOS

### Preferred Solution
- Allow users to change the request method for `updateUrl` in `capacitor.config.json`. 
- Optionally, allow the option to disable sending the user's device data (`platform`, `version_os`, `device_id`) when requesting `updateUrl` to avoid leaking data when using GET requests.

### Alternatives
N/A

### Additional Context
The default request method was changed from GET to POST in this commit https://github.com/Cap-go/capacitor-updater/commit/f763cb5b6cf8e16eb1e53c0d736289cabf7a7cfa.

**Comment by dorukeray** [comment]
+1

**Comment by WcaleNieWolny** [comment]
> Using GitHub Pages or Cloudflare Pages [as a backend for capgo updates]

This is something that was briefly considered by @riderx
It has even received a [bounty](https://github.com/Cap-go/capgo/issues/607).

Changing the method is easy - but it is not sufficient to ensure that you can use CF pages for the backend.
You CANNOT currently just host a simple, static JSON file (even with POST) because the backend is responsible for determining if the plugin is already running the latest version possible and if it is, it's the backend job to send "no new version available". A simple JSON file CANNOT do that so implementing CF pages would require a lot of changes to the plugin itself
