### ISSUE TITLE
feat: add Swift Package Manager Support

### ISSUE THREAD

**Issue by kevin-kirch** [Cap-go/capacitor-updater#443]
### Description
We are using Capacitor v6 which comes with the Swift Package Manager. It would be nice to get a support for Swift Package Manager to be compatible with the latest Version of Capacitor.

### Platform(s)
iOS

### Preferred Solution
Add Package.swift support.

**Comment by WcaleNieWolny** [comment]
I thought that swiftPM support was experimental?

> [Capacitor 6 adds experimental SPM support](https://capacitorjs.com/docs/updating/plugins/6-0)

**Comment by riderx** [comment]
@kevin-kirch we are compatible with Capacitor v6, with Pods do you get any error because of that?

**Comment by marius-se** [comment]
The problem is Capacitor v6 is, **by default**, not using (Cocoa-)Pods anymore, but Swift Package Manager. You basically can't use CapGo for new Capacitor projects without forking it and adding Swift Package Manager support. See this guide: https://capacitorjs.com/docs/ios/spm#converting-existing-plugins-to-spm

**Comment by marius-se** [comment]
So in this case we forked capacitor-updater, used the migration tool (see link above) and ripped out a lot of stuff to make it compile. It works, however it'd be great to get this upstream! Unfortunately we can't share the fork because it's... not a real fork. We just cloned the library into our monorepo. Also we deleted a lot of stuff so I think it's easier to start the migration process from scratch (which isn't too hard, probably took like an hour or two)

**Comment by riderx** [comment]
![CleanShot 2024-09-25 at 21 05 36](https://github.com/user-attachments/assets/e46e6bf4-b1cf-4448-a8a1-dd273aed8d25)
It's optional on a new project not mendatory.
We have more than 30 plugins maintained in our org, We will migrate them over time, but that not on our plan now.
And some dependency we use do not support SPM yet.

**Comment by riderx** [comment]
I think I found a way to make the updater support both without having to ripe a lot of stuff.
Can you try: **6.2.1-beta.1**

**Comment by riderx** [comment]
ok i added it

**Comment by abegehr** [comment]
@riderx, I tried 6.2.5 (and latest 6.9.0) with Capacitor v6 with SPM and am still getting the same issue:
```
Showing Recent Messages
the package manifest at '/Users/anton/local/repos/sample/node_modules/.pnpm/@capgo+capacitor-updater@6.2.5_@capacitor+core@6.2.0/node_modules/@capgo/capacitor-updater/Package.swift' cannot be accessed (/Users/anton/local/repos/sample/node_modules/.pnpm/@capgo+capacitor-updater@6.2.5_@capacitor+core@6.2.0/node_modules/@capgo/capacitor-updater/Package.swift doesn't exist in file system)
```

Checking the path, `Package.swift` is indeed missing:

<img width="517" alt="Screenshot 2025-01-06 at 14 04 51" src="https://github.com/user-attachments/assets/f1ad2556-50a3-4673-8421-e98947ffc756" />

I think the issue might be that `Package.swift` is not included in the `package.json`'s "files" list and therefore not copied over to the build folder and not included in the published npm package: https://github.com/Cap-go/capacitor-updater/blob/85918cb9d0df95cd789e6d569e766a2d365297d9/package.json#L10-L17
